import type { Metadata } from 'next'
import localFont from 'next/font/local'
import clsx from 'clsx'

import '@/styles/globals.css'

const Pretendard = localFont({
  src: '../assets/fonts/Pretendard/PretendardVariable.woff2',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(Pretendard.className)}>{children}</body>
    </html>
  )
}
